# config/packages/vich_uploader.yaml
vich_uploader:
  db_driver: orm # orm, mongodb, propel, or phpcr
  mappings:
    product_image:
      uri_prefix: /uploads/images/products
      upload_destination: '%kernel.project_dir%/public/uploads/images/products'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
      # Other options...
